title: <h1>a</h1><a href=evil.com>a</a>
description: abcd
template:
  repo: <h1>a</h1><a href=evil.com>a</a>
  name: <h1>a</h1><a href=evil.com>a</a>
before:
  - type: createIssue
    title: <h1>a</h1><a href=evil.com>a</a>
    body: new-issue.md
steps:
  - title: First step
    description: <h1>a</h1><a href=evil.com>a</a>
    event: issues.assigned
    link: '{{ 7*6 }}'
    actions:
      - type: closeIssue
